"""Add completion column to Assessment

Revision ID: 048185ee7d41
Revises: 1e4ebd8b2ccd
Create Date: 2024-10-28 18:54:08.880969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048185ee7d41'
down_revision = '1e4ebd8b2ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessment_moduleCode'), ['moduleCode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_moduleCode'))
        batch_op.drop_column('completion')

    # ### end Alembic commands ###
